name: quantum_computing
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - aws-c-auth=0.9.3=h1ddaa69_0
  - aws-c-cal=0.9.13=h6ee9776_1
  - aws-c-common=0.12.6=hc919400_0
  - aws-c-compression=0.3.1=h16f91aa_9
  - aws-c-event-stream=0.5.7=h9ae9c55_1
  - aws-c-http=0.10.7=h5928ca5_5
  - aws-c-io=0.23.3=hbe03c90_5
  - aws-c-mqtt=0.13.3=haf5c5c8_11
  - aws-c-s3=0.11.3=h8da9771_1
  - aws-c-sdkutils=0.2.4=h16f91aa_4
  - aws-checksums=0.2.7=h16f91aa_5
  - aws-crt-cpp=0.35.4=h74951b9_0
  - aws-sdk-cpp=1.11.606=h4e1b0f7_10
  - azure-core-cpp=1.16.1=h88fedcc_0
  - azure-identity-cpp=1.13.2=h853621b_1
  - azure-storage-blobs-cpp=12.15.0=h10d327b_1
  - azure-storage-common-cpp=12.11.0=h7e4aa5d_1
  - azure-storage-files-datalake-cpp=12.13.0=hb288d13_1
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.6=hc919400_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.13.7=py313hd8ed1ab_100
  - cramjam=2.11.0=py313h54b25eb_2
  - debugpy=1.8.17=py313hc37fe24_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fastparquet=2024.11.0=py313hc577518_1
  - fsspec=2025.12.0=pyhd8ed1ab_0
  - gflags=2.2.2=hf9b8971_1005
  - glog=0.7.1=heb240a5_0
  - icu=75.1=hfee45f7_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh92f572d_0
  - ipython=9.5.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - krb5=1.21.3=h237132a_0
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libarrow=22.0.0=he6e817a_6_cpu
  - libarrow-acero=22.0.0=hc317990_6_cpu
  - libarrow-compute=22.0.0=h75845d1_6_cpu
  - libarrow-dataset=22.0.0=hc317990_6_cpu
  - libarrow-substrait=22.0.0=h144af7f_6_cpu
  - libblas=3.11.0=4_h51639a9_openblas
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcblas=3.11.0=4_hb0561ab_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.17.0=hdece5d2_1
  - libcxx=21.1.1=hf598326_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - libgcc=15.2.0=hcbb3090_16
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libgoogle-cloud=2.39.0=head0a95_0
  - libgoogle-cloud-storage=2.39.0=hfa3a374_0
  - libgrpc=1.73.1=h3063b79_1
  - libiconv=1.18=h23cfdf5_2
  - liblapack=3.11.0=4_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libmpdec=4.0.0=h5505292_0
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopentelemetry-cpp=1.21.0=he15edb5_1
  - libopentelemetry-cpp-headers=1.21.0=hce30654_1
  - libparquet=22.0.0=h0ac143b_6_cpu
  - libprotobuf=6.31.1=h658db43_2
  - libre2-11=2025.11.05=h91c62da_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.50.4=h4237e3c_0
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.22.0=h14a376c_1
  - libutf8proc=2.11.2=hd2415e0_0
  - libxml2=2.15.1=h9329255_0
  - libxml2-16=2.15.1=h0ff4647_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.7=h4a912ad_0
  - lz4-c=1.10.0=h286801f_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.12.0=h248ca61_1
  - openssl=3.6.0=h5503f6c_0
  - orc=2.2.1=h4fd0076_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyh145f28c_0
  - platformdirs=4.4.0=pyhcf101f3_0
  - prometheus-cpp=1.3.0=h0967b3e_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.0=py313h6535dbc_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.13.7=h5c937ed_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.13.7=h4df99d1_100
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=8_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=27.1.0=py312hd65ceae_0
  - re2=2025.11.05=h64b956e_0
  - readline=8.2=h1d1bf99_2
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=hada39a4_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=h892fb3f_2
  - tornado=6.5.2=py313hcdf3177_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zstd=1.5.7=hbf9d68e_6
  - pip:
      - annotated-types==0.7.0
      - anyio==4.12.0
      - appdirs==1.4.4
      - astunparse==1.6.3
      - autograd==1.8.0
      - autoray==0.7.2
      - cachetools==6.2.0
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - click==8.3.1
      - contourpy==1.3.3
      - cryptography==46.0.1
      - cycler==0.12.1
      - diastatic-malt==2.15.2
      - dill==0.4.0
      - filelock==3.20.0
      - fonttools==4.60.0
      - gast==0.6.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.2.2
      - ibm-cloud-sdk-core==3.24.2
      - ibm-platform-services==0.68.3
      - idna==3.10
      - kiwisolver==1.4.9
      - matplotlib==3.10.6
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==2.3.3
      - pandas==2.3.2
      - pennylane==0.42.3
      - pennylane-lightning==0.42.0
      - pillow==11.3.0
      - pyarrow==22.0.0
      - pycparser==2.23
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydot==4.0.1
      - pyjwt==2.10.1
      - pylatexenc==2.10
      - pyparsing==3.2.5
      - pyspnego==0.12.0
      - pyyaml==6.0.2
      - qiskit==2.2.0
      - qiskit-aer==0.17.2
      - qiskit-ibm-experiment==0.4.8
      - qiskit-ibm-provider==0.11.0
      - qiskit-ibm-runtime==0.41.1
      - requests==2.32.5
      - requests-ntlm==1.3.0
      - rustworkx==0.17.1
      - scipy==1.16.2
      - scipy-openblas32==0.3.30.0.2
      - seaborn==0.13.2
      - shellingham==1.5.4
      - stevedore==5.5.0
      - sympy==1.14.0
      - termcolor==3.1.0
      - tomlkit==0.13.3
      - tqdm==4.67.1
      - typer-slim==0.20.0
      - typing-inspection==0.4.1
      - urllib3==2.5.0
      - websocket-client==1.8.0
      - websockets==15.0.1
      - wheel==0.45.1
prefix: /Users/victoryma/miniconda3/envs/quantum_computing
